[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[services.treehole-relay]
source = "."

[services.treehole-relay.variables]
NODE_ENV = "production"
PORT = "9001"
WS_PORT = "9002"
HEALTH_PORT = "3000"